sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  # Stack
  - ghc: 8.8.3
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  - |
    curl -sSL https://get.haskellstack.org/ | sh

    # build project with stack
    stack --version
    stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

script:
  - stack test --system-ghc

notifications:
  email: false

